tap "anomalyco/tap"
tap "hashicorp/tap"
tap "nikitabobko/tap"
# Pluggable and configurable code formatting platform written in Rust
brew "dprint"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Remote repository management made easy
brew "ghq"
# Distributed revision control system
brew "git"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Polyglot runtime manager (asdf rust clone)
brew "mise"
# Incremental parsing library
brew "tree-sitter"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Reattach process (e.g., tmux) to background
brew "reattach-to-user-namespace"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Terminal multiplexer
brew "tmux"
# Parser generator tool
brew "tree-sitter-cli"
# The AI coding agent built for the terminal.
brew "anomalyco/tap/opencode", trusted: true
# Terraform
brew "hashicorp/tap/terraform", trusted: true
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Command-line interface for 1Password
cask "1password-cli"
cask "aerospace"
# Voice and text chat software
cask "discord"
# App to build and share containerised applications and microservices
cask "docker-desktop"
cask "font-mononoki-nerd-font"
# Set of tools to manage resources and applications hosted on Google Cloud
cask "gcloud-cli"
# Web browser
cask "google-chrome"
# Keyboard customiser
cask "karabiner-elements"
# Shows the next meeting in the menu bar
cask "meetingbar"
# Control your tools with a few keystrokes
cask "raycast"
# Team communication and collaboration software
cask "slack"
# Free and open-source OpenVPN client
cask "tunnelblick"
