general.import = [
  "~/.config/alacritty/themes/themes/solarized_dark.toml"
]

[[keyboard.bindings]]
chars = '\'
key = "¥"

[[keyboard.bindings]]
chars = "¥"
key = "¥"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B"
key = "LBracket"
mods = "Control"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "mononoki Nerd Font"
style = "Bold"

[font.bold_italic]
family = "mononoki Nerd Font"
style = "Bold Itali"

[font.italic]
family = "mononoki Nerd Font"
style = "Italic"

[font.normal]
family = "mononoki Nerd Font"
style = "Regular"
