name: Test

on:
  push:
    branches: [ master ]
  pull_request:

jobs:

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:

    - name: Entry Point MacOS
      if: runner.os == 'macOS'
      run: |
        bash -c "$(curl -L raw.githubusercontent.com/dondakeshimo/dotfiles/$GITHUB_SHA/setup/entrypoint/mac_full.sh)"

    - name: Entry Point Ubuntu
      if: runner.os == 'Linux'
      run: |
        bash -c "$(curl -L raw.githubusercontent.com/dondakeshimo/dotfiles/$GITHUB_SHA/setup/entrypoint/apt_full.sh)"

    - name: Deploy
      run: |
        ~/src/github.com/dondakeshimo/dotfiles/setup/deployer/symlink.sh all

    - name: Test bash
      run: |
        source $HOME/.bash_profile

    - name: Test vim
      run: |
        vim .vimrc &

    - name: Test nvim
      run: |
        nvim .vimrc &

    - name: Test tmux
      run: |
        tmux new -s test -d

    # "Test zsh" confirm only zsh file sourced by .zshrc
    - name: Test zsh
      run: |
        for f in $HOME/.zsh/[0-9]*.(sh|zsh) do source "$f" done
      shell: zsh {0}
      env:
        TMUX: test
